name: Test

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  python:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        python:
        - '3.6'
        - '3.7'
        - '3.8'
        - '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel pytest
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y swig
    - uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
        key: ${{ runner.os }}-chocolatey-python-1
        restore-keys: |
          ${{ runner.os }}-chocolatey-python-
          ${{ runner.os }}-chocolatey-
    - name: Select build type
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: echo "BUILD_TYPE=Release" >> $GITHUB_ENV
    - name: Select build type
      if: matrix.os != 'windows-latest'
      run: echo "BUILD_TYPE=Debug" >> $GITHUB_ENV
    - name: Build
      env:
        NPROCS: 100
      run: python -m pip install --verbose .
    - name: Test
      # No (automated) tests yet, and knowing me there probably won't be any.
      # Just see if the thing loads correctly when imported.
      #run: python -m pytest
      run: python -c 'import gerbertools'
